import Head from "next/head";
import type { NextPage } from "next";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="grid place-items-center h-screen ">
        <div className="flex flex-col">
          <h1 className="overflow-hidden border-r-2 border-orange-500 whitespace-nowrap tracking-widest animate-typing text-5xl my-0 mx-auto inline-block">
            Hello! My name is Colin
          </h1>
        </div>
      </main>
    </>
  );
};

export default Home;
