import Header from "next/head";

const Head = () => (
  <Header>
    <title>Colin&apos;s Website</title>
    <meta name="description" content="Generated by create-t3-app" />
    <link rel="icon" href="/favicon.ico" />
  </Header>
);

export default Head;
